name: Build After Deploy
on:
  pull_request:
    branches:
      - qa
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests 🧪
        run: |
          echo --- Run Test 🧪---
          docker-compose run --rm zenticket-ci sh -c "composer install --no-interaction && XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage-result.xml --log-junit=execution-result.xml --testdox"
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: bin
      - name: Clone Repository
        uses: actions/checkout@master
      - name: Download code coverage results
        uses: actions/download-artifact@v1
        with:
          name: code-coverage-report
          path: |
            coverage-result.xml
            execution-result.xml
      - name: Sonar Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
